@startuml

title  Реестр событий оформления заказа

actor Пользователь

participant Сервис_корзины
participant Сервис_складов
participant Сервис_платежей

Пользователь -> Сервис_корзины :  Подтверждение заказа()
Сервис_корзины -> Сервис_складов : Событие: Состав заказа подтвержден
Сервис_складов -> Сервис_складов : Проверка/Резервирование товара()
group
Сервис_складов -> Сервис_корзины : Событие: Резервирование выполнено
Сервис_складов -> Сервис_платежей : Событие: Резервирование выполнено
end
Сервис_корзины -> Сервис_корзины: Изменение статуса заказа()
Сервис_платежей -> Сервис_платежей: Проведение платежа()
group
Сервис_платежей -> Сервис_складов: Событие: Платеж проведен
Сервис_платежей -> Сервис_корзины: Событие: Платеж проведен 
end
Сервис_корзины -> Сервис_корзины: Изменение статуса заказа()
Сервис_складов -> Сервис_складов: Передача в службу доставки()
Сервис_складов -> Сервис_корзины: Событие: передано в доставку
Сервис_корзины -> Сервис_корзины: Изменение статуса заказа()

@enduml